### ISSUE TITLE
Created rotseutil and rotsedatamodel branch

### ISSUE THREAD

**Issue by danielsela42** [rotsehub/rotseutil#3]
Hello Dr. Kehoe and Mr. Dhungana,

I uploaded the rotesutil and rotsedatamodel files I had to the branch 1.0.5rc (release candidate). On rotseutil, I have the added folder and new license. The README.rst links to the README.rst in docs. If there is anything that needs to be fixed, please let me know.

Best regards

**Comment by gdhungana** [comment]
@danielsela42 good work! The documents seems to be saying more than what is available here. One comment is that we do not want to write every possible functions to a file for generic functions. Rather we can develop a single module (say astroutility or rotseutility) such that different functions can be imported from that common module. We can start from here, and keep developing. Once @rkehoe can review this and this finally merges, I have other general purpose astrophysics transformations etc, which I can add here.

**Comment by rkehoe** [comment]
@gdhungana and @danielsela42, this looks like progress!  I see files in both rotseutil and rotsedatamodel.  It is unclear where the README’s are so that I might run these codes, but it is good to get the code in at this point.  

I can’t really assess the repos until we are to the point of something runnable, and then we should do a Pull Request, right @gdhungana?  

I think for now, I would encourage you to get the general code and other code into here, or into rotsedatamodel.  If you could work on readme files so that a user got know how to run each item, that would help, but I would rather get working go into the repo before requiring readme files.

BTW, the ‘rotseana’ area is misnamed ‘rosteana’ — can somebody change that?  

Also, @gdhungana, didn’t you have a concern about making code total public and a problem with github versus other code management mechanisms.  We should resolve that very soon — but for now let s get what we have in place.

Lastly, I think we will want to also get Grant Donnelly’s code into here.  I will mention it to him on Monday and hopefully he can do that in the next couple weeks.  I’ll wait till your next updates.  BTW, let’s not meet this Saturday, but the following one!

**Comment by gdhungana** [comment]
@rkehoe I'll provide an example test run for the data management code tomorrow. But I don't think we can add all the use cases and runs for all that goes here. May be just the main scripts test runs with enough information on data and environment. Perhaps we can work on here for all the general purpose work in public repo, and if we find something sensitive, we may want to create a private repo. I have not made one myself, but I am sure there is a way to do that if needed.

**Comment by danielsela42** [comment]
@rkehoe Unfortunately, I cannot meet on Saturdays anymore; I have something until 5:00-5:30. Is there any other day that might work?

**Comment by rkehoe** [comment]
Hi Daniel,

Okay, I will give it some thought.  We will try an evening time, but need to work it out with Govinda and my family.

Bob

Sent from my iPad

On Apr 22, 2019, at 8:15 PM, danielsela42 <notifications@github.com<mailto:notifications@github.com>> wrote:


@rkehoe<https://github.com/rkehoe> Unfortunately, I cannot meet on Saturdays anymore; I have something until 5:00-5:30. Is there any other day that might work?

**Comment by gdhungana** [comment]
@rkehoe I have fixed some typo, did some tests and updated the README for the M2 data managing script. I apparently do not have write permissions there, so could not test there, but you should be able to run without any issue (hopefully :)). Please check and let me know if the code crashes or more information is needed. Once you test it for a single directory, I can update to loop over several directories in one go. 

I can be available during the weekday evenings but it will be only around ~6:30 or so.

**Comment by rkehoe** [comment]
@gdhungana Can you take a look at this Issue and indicate the statue of it?  I am working to close obsolete or completed Issues.

**Comment by rkehoe** [comment]
@gdhungana, @danielsela42 I am closing this issue as old.
