### ISSUE TITLE
Histogram, Mean, and RMS power point

### ISSUE THREAD

**Issue by danielsela42** [rotsehub/rotseutil#6]
@rkehoe I compiled the histograms, mean, and rms for 7x7, 12x12, and 20x20 subimages in google slides. Here is the link: https://docs.google.com/presentation/d/1mCewmipTSqZL1DCg7T3xDcg6shcWhNxCOZg-8Ed8lZI/edit?usp=sharing.

**Comment by rkehoe** [comment]
@danielsela42 Thanks.  I sent my comments by email, but here’s a summary.  The ROTSE1 and ROTSE3 results look surprisingly similar, except for the spikes at zero in the latter.  In order to figure out what is going on there, you would need to identify the RA and Dec of the subimages where the zeros are happening.  Then look at some of the images to see if there are indeed no stars in that part of the image.  I assume there are no exposures that have zeros for all of their subimages, right?  You can plot the # of subimages with zeros in a histogram.  If this is happening, you will see a exposures that have the maximum number of subimages with zeros.
